#!/usr/bin/env python3
"""Turn font glyphs into Android vector drawables (+ level-lists).

Widgets cannot rely on @font/ resources: on the test phone (ColorOS launcher) a bundled font is
ignored inside RemoteViews and the text falls back to the system font. Vector drawables are
resolution independent, need no font, and can be selected with ImageView.setImageLevel.

Usage: python3 tools/gen_glyphs.py   (run from the project root; needs fonttools)
"""
import os
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen

RES = 'android/app/src/main/res/'
DRAWABLE = RES + 'drawable/'

# name prefix, font, glyph list, vertical box (font units, bottom..top), dp per font unit, fill
SETS = [
    # pastel face: em 105 dp (Lilita One, upem 1000); tinted per digit slot in the layout
    ('pastel', 'font/lilita.ttf', '0123456789', (-12, 712), 105 / 1000, '#FFFFFFFF'),
    # LED side text: 7-segment digits; same box for all digits so every slot has equal width
    ('seg', 'font/segments.otf', '0123456789', (-222, 904), 1 / 100, '#FF00FF00'),
]
# single glyphs / words that are not digits: (file name, font, text, box, dp per unit, fill)
EXTRA = [
    ('seg_slash', 'font/segments.otf', '/', (-222, 904), 1 / 100, '#FF00FF00'),
    ('seg_am', 'font/segments.otf', 'AM', (45, 1000), 1 / 100, '#FF00FF00'),
    ('seg_pm', 'font/segments.otf', 'PM', (45, 1000), 1 / 100, '#FF00FF00'),
]


def fmt(v):
    return ('%.1f' % v).rstrip('0').rstrip('.')


def glyph_vector(font, text, box, scale, fill):
    gs = font.getGlyphSet()
    cmap = font.getBestCmap()
    bottom, top = box
    pen = SVGPathPen(gs, ntos=fmt)
    x = 0
    for ch in text:
        name = cmap[ord(ch)]
        # flip y (font y goes up, vector y goes down) and shift by the advance so far
        gs[name].draw(TransformPen(pen, (1, 0, 0, -1, x, top)))
        x += font['hmtx'][name][0]
    width = x
    height = top - bottom
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- generated by tools/gen_glyphs.py from the font glyph outlines -->\n'
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="%sdp"\n    android:height="%sdp"\n'
        '    android:viewportWidth="%s"\n    android:viewportHeight="%s">\n'
        '    <path android:fillColor="%s" android:pathData="%s" />\n'
        '</vector>\n' % (fmt(width * scale), fmt(height * scale), fmt(width), fmt(height), fill, pen.getCommands())
    )


def write(name, content):
    with open(DRAWABLE + name + '.xml', 'w') as f:
        f.write(content)


for prefix, path, glyphs, box, scale, fill in SETS:
    font = TTFont(RES + path)
    for ch in glyphs:
        write('%s_%s' % (prefix, ch), glyph_vector(font, ch, box, scale, fill))
    items = '\n'.join(
        '    <item android:drawable="@drawable/%s_%s" android:maxLevel="%s" android:minLevel="%s" />' % (prefix, ch, ch, ch)
        for ch in glyphs)
    write('%s_digit' % prefix, (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- selects one %s digit by image level (0-9); generated by tools/gen_glyphs.py -->\n'
        '<level-list xmlns:android="http://schemas.android.com/apk/res/android">\n%s\n</level-list>\n' % (prefix, items)))

for name, path, text, box, scale, fill in EXTRA:
    write(name, glyph_vector(TTFont(RES + path), text, box, scale, fill))
print('done')
